### ISSUE TITLE
Ethernet Padding Bug for empty1 test

### ISSUE THREAD

**Issue by jrihds** [oryxlabs/PolarDNS#6]
Hello
I think I have found an Ethernet padding test bug. For me, the dig command for the 'empty1.yourdomain.com' test returns a Warning banner for queries sent across the internet to a remote instance of PolarDNS, but not for queries to a localhost instance of PolarDNS.

Internet bound query:
```
$ dig empty1.yourdomain.com @<remote-ip> +tries=1 +timeout=3 -p 53
;; Warning: short (< header size) message received
;; communications error to <remote-ip>#53: timed out

; <<>> DiG 9.18.10 <<>> empty1.yourdomain.com @<remote-ip> +tries=1 +timeout=3 -p 53
;; global options: +cmd
;; no servers could be reached
```
Local query:
```
$ dig empty1.yourdomain.com @127.0.0.1 +tries=1 +timeout=3 -p 53
;; communications error to 127.0.0.1#53: timed out

; <<>> DiG 9.18.10 <<>> empty1.yourdomain.com @127.0.0.1 +tries=1 +timeout=3 -p 53
;; global options: +cmd
;; no servers could be reached
```
This means the md5sum is different so the test might fail. I've checked this difference in Wireshark and I think it is due to extra Ethernet frame padding on the internet query which isn't present on the loopback query. The Warning could be stripped off using the `grep -v` command in `test.sh` but the hashes for other 'empty' tests would need to be adjusted to accommodate this.

**Comment by ivan-jedek** [comment]
Thank you for the bug report, @jrihds, much appreciated!

I came to the same results as you, the `dig` command simply returns additional line in the output when this test is run remotely.

To be frank, I never expected the tests to be run remotely.

Rather than additional `grep -v` , I have removed this particular test from the `test.sh`. The tests are far from perfect, there's whole lot of constrains, for example lot of them will fail when using non-com domain.

We plan to improve the tests in the future and go with pytest..

In any case, for now this test should not be a problem anymore.
